build:
  maxIssues: 0

complexity:
  LongMethod:
    threshold: 60
    ignoreAnnotated:
      - 'Composable'
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 8
    ignoreAnnotated:
      - 'Composable'

naming:
  FunctionNaming:
    functionPattern: '[a-z][a-zA-Z0-9]*'
    ignoreAnnotated:
      - 'Composable'
  PackageNaming:
    packagePattern: '[a-z][a-zA-Z0-9_]*(\.[a-z][a-zA-Z0-9_]*)*'

style:
  active: false
